apiVersion: v2
name: mqtt2nats
description: Bidirectional NATS <-> MQTT 5.0 bridge
type: application
version: "0.1.0"
appVersion: "0.1.0"
kubeVersion: ">=1.25.0-0"
home: https://github.com/josh/mqtt2nats
sources:
  - https://github.com/josh/mqtt2nats
keywords:
  - mqtt
  - nats
  - jetstream
  - bridge
maintainers:
  - name: Joshua Peek
